name: Continuous Integration
on: [push, pull_request]
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  backend-build-and-test:
    name: (Backend) Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js v18
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: backend/package-lock.json
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: cd backend && npm install

      - name: Type Check
        run: tsc --noEmit

      - name: Run tests
        run: npm test
        env:
          # Required for session encryption
          SESSION_ENCRYPTION_KEY: ${{ secrets.GITHUB_TOKEN }}
